export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const EMPTY_CART = "EMPTY_CART";
export const SAVE_CART_START = "SAVE_CART_START";
export const SAVE_CART_FAILED ="SAVE_CART_FAILED"
export const SAVE_CART_SUCCESS ="SAVE_CART_SUCCESS"


