export const PRODUCT_LOADING_STARTED = "PRODUCT_LOADING_STARTED";
export const PRODUCT_LOADING_SUCCESS = "PRODUCT_LOADING_SUCCESS";
export const PRODUCT_LOADING_FAILED = 'PRODUCT_LOADING_FAILED'
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const PERSISTED_USER = "PERSISTED_USER"

export const CART_LOAD = "CART_LOAD"