export const LOADING_STARTED = "LOADING_STARTED";
export const LOADING_SUCCESS = "LOADING_SUCCESS";
export const LOADING_FAILED = 'LOADING_FAILED'
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
